language: php

php:
    - 7.1

before_script:
    - chmod -R 777 bootstrap/cache
    - chmod -R 777 storage
    - mysql -e 'create database testing;'
    - composer self-update
    - composer install --no-interaction

script:
    - vendor/bin/phpunit
