language: php
php:
- 7.1
before_install:
- nvm install node
before_script:
- chmod -R 777 bootstrap/cache
- chmod -R 777 storage
- cp .env.travis .env
- mysql -e 'create database testing;'
- composer self-update
- composer install --no-interaction
- npm install
- php artisan key:generate
script:
- vendor/bin/phpunit
- npm run test
after_script:
- npm run prod
deploy:
  provider: script
  script: bash scripts/travis-deploy.sh
  on:
    tags: true
