version: 0.0

os: linux

files:
    - source: /
      destination: /home/ubuntu/medscanner

permissions:
    - object: /home/ubuntu/medscanner
      pattern: "**"
      owner: ubuntu
      group: ubuntu
      mode: 4750
      type:
          - directory
    - object: /home/ubuntu/medscanner
      pattern: "**"
      owner: ubuntu
      group: ubuntu
      mode: 640
      type:
          - directory

hooks:
    ApplicationStop:
        - location: scripts/application-stop.sh
          timeout: 30
          runas: root
    BeforeInstall:
        - location: scripts/before-install.sh
          timeout: 300
          runas: root
    AfterInstall:
        - location: scripts/after-install-www.sh
          timeout: 300
          runas: ubuntu
        - location: scripts/after-install-root.sh
          timeout: 30
          runas: root
    ApplicationStart:
        - location: scripts/application-start.sh
          timeout: 30
          runas: root
